# Generated by Django 4.1.5 on 2023-02-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColumnName', models.CharField(max_length=100, verbose_name='Column name')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskName', models.CharField(max_length=100, verbose_name='Desk name')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoryName', models.CharField(max_length=100, verbose_name='Story name')),
                ('Description', models.CharField(max_length=300, verbose_name='Description')),
                ('DueDate', models.DateField(verbose_name='Date of completion')),
                ('StoryEstimation', models.IntegerField(verbose_name='Story estimation')),
                ('Column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stories', to='todolist.column')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=50, verbose_name='Task name')),
                ('IsCompleted', models.BooleanField(verbose_name='Completed')),
                ('Story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='todolist.story')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='Desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Columns', to='todolist.desk'),
        ),
    ]
